# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c7403b53d654741ffca237519f0bc660fd472b0b1ab1751fa6fe5e115da8d7bebc4a79fe08aed2f2de24942365a7abf351a8ccd867b8e13f1a0a04e5a3bde4c

test:
  secret_key_base: c3c16cd01ec21febb6707d5a281375c2e541b1e1c2d552f3f481d074de1675419a7f3072b3676fe0dee029086fdf6a16ad108b998568bc7ca1dfcc23566a3ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
